apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: default
      volumes:
      - name: gs-credentials
        secret:
          secretName: gs-credentials
      containers:
      - name: api
        image: asia.gcr.io/django-project-368202/server
        ports:
        - containerPort: 8000
        command: ['gunicorn', 'app.wsgi:application', '-b', '0.0.0.0:8000']
        volumeMounts:
          - mountPath: /gs
            name: gs-credentials
        env:
        - name: STATIC_URL
          value: https://storage.googleapis.com/k8s-demo-scottman625-bucket/static/
        - name: POSTGRES_SERVICE_HOST
          value: 10.91.71.5
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
        #   value: postgres
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: GS_BUCKET_NAME
          value: k8s-demo-scottman625-bucket
        
      # - name : cloud-sql-proxy
      #   image: gcr.io/cloudsql-docker/gce-proxy:1.28.0
      #   imagePullPolicy: Always
        
      #   command:
      #   - "/cloud_sql_proxy"

      #   - "-log_debug_stdout"


      #   - "-instances=postgres=tcp:5432"
      #   securityContext:

      #     runAsNonRoot: true

      #   resources:
      #     requests:
      #       memory: "2Gi"
      #       cpu:    "1"
        
        
